spring:
  jpa:
    hibernate:
      ddl-auto: update # Configura cómo se debe gestionar el esquema de la base de datos.
  datasource:
    url: jdbc:mysql://localhost:3306/incidencias?createDatabaseIfNotExist=true # URL de conexión a la base de datos MySQL.
    username: root # Nombre de usuario para conectarse a la base de datos.
    password: toor # Contraseña correspondiente al usuario especificado.
    hikari: # Hikari es un mecanismo de eficiencia de conexiones. Conocido como "Pool de conexiones".
      connection-timeout: 60000 # Establece el tiempo máximo de espera en milisegundos (60 segundos) para obtener una conexión antes de lanzar un error.
      maximum-pool-size: 5 # Especifica el número máximo de conexiones permitidas en el pool de conexiones simultáneas.
  http:
    encoding:
      charset: UTF-8 # Define la codificación para las respuestas HTTP.
      enabled: true # Habilita explícitamente la codificación HTTP.
      force: true # Obliga a que todas las respuestas sean UTF-8.
  mail:
      host: smtp.gmail.com
      port: 587
#      username: jjurval099@g.educaand.es
#      password: siil xgbb voep bbdg
      username: ${MAIL_USERNAME}      
      password: ${MAIL_API_KEY}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
server:
  port: 8888 # Define el puerto en el que se ejecutará la aplicación Spring Boot.

logging: # Sección de configuración del sistema de logs en Spring.
  level:
    ies.jandula: DEBUG # Define el nivel de log (recursivo).
  file:
    name: registro.log # Ruta y el nombre del archivo donde se guardarán los logs.
    max-size: 1MB # Define el tamaño máximo que puede tener el archivo de log antes de que se cree uno nuevo.
    max-history: 20 # Especifica el número máximo de archivos históricos de logs que se guardarán.
reaktor:
  publicKeyFile: "C:/claves/public_key.pem"
  urlCors: "http://localhost:8888, http://localhost:5173, http://192.168.1.209:5173, http://192.168.1.181:5173, http://192.168.1.137:5173, http://172.20.10.2:5173"
  clientId: "bookings"
  constantes:
    reservasFijas: ""
    reservasPuntuales: ""
  firebase_server_url: "http://localhost:8083"
  users_timeout: 30000
  http_connection_timeout: 30000


